### ISSUE TITLE
Chromium based Browser MS-Edge

### ISSUE THREAD

**Issue by clubmasterfu** [dwisiswant0/galer#26]
I´ve the same Issue cause i´m using the chromium based MS-Edge Browser. Is it possible to use this engine by setting the Path manually? I installed the Go library for headless "chromedp" but also doesn´t work.  Thx for your reply.

_Originally posted by @clubmasterfu in https://github.com/dwisiswant0/galer/issues/4#issuecomment-782850960_

**Comment by dwisiswant0** [comment]
We'll check it out.
