### ISSUE TITLE
[BUG] Error cannot fetch URL.

### ISSUE THREAD

**Issue by ZorD1** [dwisiswant0/galer#28]
**Describe the bug**

It cannot recognize any url that is passed to it.
Example:
galer -u 'https://twitter.com'

**To Reproduce**

No matter which method is used, it always reflects the same error, even if a file is passed to it with the urls or is used 
- cat urls.txt  | galer
- galer -u urls.txt
- galer -u https://twitter.com/

**Environment (please complete the following information):**

- OS: Ubuntu 20.04 LTS / WSL 2
- OS version: Linux HP-PavilionGaming 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- galer version: v0.0.2

**Comment by Tedixx** [comment]
Having the same issue

**Comment by ruzfi** [comment]
Hi @ZorD1,

I recently tried to reproduce this problem using my macOS and freshly installed debian, and the result is my macOS can run this tool perfectly but on freshly installed debian it gets the same `cannot fetch URL` error message.

after using the `--verbose` flag on a freshly installed debian it looks like this tool requires `google-chrome` installed #4 
```[ERR] Error 'https://twitter.com': exec: "google-chrome": executable file not found in $PATH.```

Just to make sure that the error is the same, can you provide any information using `--verbose` flag?

**Comment by ruzfi** [comment]
#4

**Comment by vansh1** [comment]
i am attaching a screenshot, i have added some effects in it to hide urls but errors are readble 
![Screenshot (25)](https://user-images.githubusercontent.com/29426059/196277232-24543a77-6401-4c91-a5e5-44cd39ef86e6.jpg)

**Comment by vansh1** [comment]
![Screenshot (26)](https://user-images.githubusercontent.com/29426059/196284853-6f4d5f64-4895-4507-bd5d-3108bb48a48c.png)
