### ISSUE TITLE
Can't fetch URL Error

### ISSUE THREAD

**Issue by melbadry9** [dwisiswant0/galer#4]
**Describe the bug**
I'm getting the following error with all valid URLs

**To Reproduce**
By using `-u` arg or using `stdin`

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/43918685/100840134-1eab5280-347e-11eb-86f3-031654795169.png)

**Environment (please complete the following information):**

- OS: Debian 10
- OS version: `4.19.0-11-cloud-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux`
- galer version: latest

**Comment by dwisiswant0** [comment]
Guess it's your connection problem, working fine on my side, @melbadry9. Try to use `-v/--verbose`.

![Screenshot_2020-12-02_15-35-55](https://user-images.githubusercontent.com/25837540/100848831-40273100-34b4-11eb-8cf3-ea7341e40a5b.png)

**Comment by melbadry9** [comment]
I see that i don’t have google chrome installed, and that causing this problem. You should have added this part on README.md as i didn’t know it depends on a specific web browser.

**Comment by dwisiswant0** [comment]
Can you give an details with `--verbose`, @melbadry9?

**Comment by dwisiswant0** [comment]
Dunno why are you facing this, I've tried on my VPS and work as well.

**Comment by melbadry9** [comment]
google-chrome was not installed and that caused the issue, so after installing it was solved. Thanks

**Comment by clubmasterfu** [comment]
I´ve the same Issue cause i´m using the chromium based MS-Edge Browser. Is it possible to use this engine by setting the Path manually? I installed the Go library for headless "chromedp" but also doesn´t work.  Thx for your reply.

**Comment by vansh1** [comment]
i am using ubuntu terminal how can i solve this same issue
