### ISSUE TITLE
[BUG]cannot parse url

### ISSUE THREAD

**Issue by vansh1** [dwisiswant0/galer#53]
**Describe the bug**

**To Reproduce**

cat httpx.txt | galer -o galer.txt --verbose
**Expected behavior**

it should run brings some js files .

**Screenshots**

**Environment (please complete the following information):**

- OS: ubuntu
- Linux kalibox 5.11.0-1025-azure
- galer version: latest(just installed galer)

**Additional context**
Add any other context about the problem here. Full output log is probably a helpful thing to add here.

**Comment by ruzfi** [comment]
Hi @vansh1,

Can you provide example `httpx.txt` file that causing cannot parse url message?

After reviewing the error messages coming from the lines https://github.com/dwisiswant0/galer/blob/7e0f77b14fb58288f2afc34575022ceffc86f7aa/pkg/galer/galer.go#L32-L34 and https://github.com/dwisiswant0/galer/blob/7e0f77b14fb58288f2afc34575022ceffc86f7aa/pkg/galer/util.go#L8-L20 there seems to be a url typing error, try to make sure it fits the URL structure as this tool requires URL scheme and URL host to run

The URL structure i mention is
`[scheme:][//[userinfo@]host][/]path[?query][#fragment]`
e.g.
`https://twitter.com`

**Comment by vansh1** [comment]
i am still getting error
[ERR] Error 'https://subdomain.target.com': cannot fetch URL.

**Comment by nAgga3** [comment]
I have the same errror

**Comment by hxlxmj** [comment]
Same error
